import { describe, expect, test } from "vitest";

import { graph } from "./graph";

describe("Graph", () => {
  test("graphs", () => {
    const df = [...graph(conns).nodes];

    expect(df.map((j) => j.id)).toEqual([
      "BOB",
      "PHYS",
      "DOGS",
      "ALB",
      "PIE",
      "PNTN",
      "BOOK",
    ]);
  });
});

const conns = [
  { category: "Science", human: "BOB", id: "PHYS", label: "Physics" },
  { category: "Science", human: "BOB", id: "DOGS", label: "Doggies" },
  { category: "Science", human: "ALB", id: "PHYS", label: "Physics" },
  { category: "Art", human: "PIE", id: "PNTN", label: "Paintin" },
  { category: "Lit", human: "BOB", id: "BOOK", label: "Books" },
];

const xconns = [
  { category: "Science", human: "Q9106", id: "Q413", label: "physics" },
  { category: "Science", human: "Q9106", id: "Q413", label: "physics" },
  {
    category: "Science",
    human: "Q9106",
    id: "Q1069",
    label: "geology",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q394",
    label: "metrology",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q394",
    label: "metrology",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q2329",
    label: "chemistry",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q8134",
    label: "economics",
  },
  { category: "Science", human: "Q9021", id: "Q413", label: "physics" },
  { category: "Science", human: "Q9021", id: "Q413", label: "physics" },
  {
    category: "Science",
    human: "Q9021",
    id: "Q3194786",
    label: "quantum theory",
  },
  {
    category: "Science",
    human: "Q9021",
    id: "Q11473",
    label: "thermodynamics",
  },
  {
    category: "Science",
    human: "Q9021",
    id: "Q18362",
    label: "theoretical physics",
  },
  { category: "Science", human: "Q9106", id: "Q413", label: "physics" },
  { category: "Science", human: "Q9106", id: "Q413", label: "physics" },
  {
    category: "Science",
    human: "Q9106",
    id: "Q1069",
    label: "geology",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q394",
    label: "metrology",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q394",
    label: "metrology",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q2329",
    label: "chemistry",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q8134",
    label: "economics",
  },
  { category: "Science", human: "Q9021", id: "Q413", label: "physics" },
  { category: "Science", human: "Q9021", id: "Q413", label: "physics" },
  {
    category: "Science",
    human: "Q9021",
    id: "Q3194786",
    label: "quantum theory",
  },
  {
    category: "Science",
    human: "Q9021",
    id: "Q11473",
    label: "thermodynamics",
  },
  {
    category: "Science",
    human: "Q9021",
    id: "Q18362",
    label: "theoretical physics",
  },
  { category: "Science", human: "Q8962", id: "Q413", label: "physics" },
  { category: "Science", human: "Q8962", id: "Q413", label: "physics" },
  { category: "Science", human: "Q8753", id: "Q413", label: "physics" },
  { category: "Science", human: "Q8753", id: "Q413", label: "physics" },
  {
    category: "Science",
    human: "Q8753",
    id: "Q18334",
    label: "particle physics",
  },
  {
    category: "Science",
    human: "Q8753",
    id: "Q18362",
    label: "theoretical physics",
  },
  { category: "Science", human: "Q1589", id: "Q413", label: "physics" },
  { category: "Science", human: "Q1589", id: "Q413", label: "physics" },
  {
    category: "Science",
    human: "Q1589",
    id: "Q11190",
    label: "medicine",
  },
  { category: "Science", human: "Q1585", id: "Q413", label: "physics" },
  { category: "Science", human: "Q1585", id: "Q413", label: "physics" },
  {
    category: "Science",
    human: "Q44483",
    id: "Q7094",
    label: "biochemistry",
  },
  {
    category: "Science",
    human: "Q5333",
    id: "Q1069",
    label: "geology",
  },
  {
    category: "Science",
    human: "Q5333",
    id: "Q23498",
    label: "archaeology",
  },
  { category: "Music", human: "Q7351", id: "Q1344", label: "opera" },
  {
    category: "Music",
    human: "Q7351",
    id: "Q189201",
    label: "chamber music",
  },
  {
    category: "Music",
    human: "Q7351",
    id: "Q9730",
    label: "classical music",
  },
  {
    category: "Lit",
    human: "Q38337",
    id: "Q6689",
    label: "French literature",
  },
  {
    category: "Lit",
    human: "Q9711",
    id: "Q6689",
    label: "French literature",
  },
  {
    category: "Lit",
    human: "Q35610",
    id: "Q208505",
    label: "crime novel",
  },
  {
    category: "Lit",
    human: "Q35610",
    id: "Q20665028",
    label: "detective literature",
  },
  {
    category: "Lit",
    human: "Q35610",
    id: "Q186579",
    label: "English-language literature",
  },
  {
    category: "Science",
    human: "Q7504",
    id: "Q690200",
    label: "radiobiology",
  },
  {
    category: "Science",
    human: "Q7504",
    id: "Q2329",
    label: "chemistry",
  },
  {
    category: "Science",
    human: "Q5396",
    id: "Q3798668",
    label: "aerospace engineering",
  },
  {
    category: "Science",
    human: "Q20882",
    id: "Q20050859",
    label: "aerodynamics engineering",
  },
  {
    category: "Science",
    human: "Q42985",
    id: "Q521",
    label: "physiology",
  },
  {
    category: "Science",
    human: "Q42985",
    id: "Q521",
    label: "physiology",
  },
  {
    category: "Science",
    human: "Q762",
    id: "Q521",
    label: "physiology",
  },
  {
    category: "Science",
    human: "Q762",
    id: "Q521",
    label: "physiology",
  },
  {
    category: "Science",
    human: "Q762",
    id: "Q11023",
    label: "engineering",
  },
  { category: "Art", human: "Q762", id: "Q11629", label: "painting" },
  {
    category: "Science",
    human: "Q680",
    id: "Q521",
    label: "physiology",
  },
  {
    category: "Science",
    human: "Q680",
    id: "Q521",
    label: "physiology",
  },
  {
    category: "Science",
    human: "Q21186",
    id: "Q182468",
    label: "hydrography",
  },
  {
    category: "Science",
    human: "Q30769",
    id: "Q874429",
    label: "group theory",
  },
  {
    category: "Science",
    human: "Q30769",
    id: "Q28575007",
    label: "theory of differential equations",
  },
  {
    category: "Science",
    human: "Q30769",
    id: "Q8087",
    label: "geometry",
  },
  {
    category: "Art",
    human: "Q6682",
    id: "Q1027879",
    label: "graphics",
  },
  {
    category: "Lit",
    human: "Q6682",
    id: "Q1233720",
    label: "young adult literature",
  },
  {
    category: "Art",
    human: "Q6682",
    id: "Q2921001",
    label: "art of drawing",
  },
  { category: "Art", human: "Q6682", id: "Q11629", label: "painting" },
  {
    category: "Art",
    human: "Q6682",
    id: "Q36649",
    label: "visual arts",
  },
  {
    category: "Science",
    human: "Q7200",
    id: "Q1066186",
    label: "study of history",
  },
  {
    category: "Science",
    human: "Q20710",
    id: "Q83042",
    label: "neurology",
  },
  {
    category: "Science",
    human: "Q20710",
    id: "Q7867",
    label: "psychiatry",
  },
  {
    category: "Science",
    human: "Q20710",
    id: "Q11190",
    label: "medicine",
  },
  {
    category: "Science",
    human: "Q9215",
    id: "Q83042",
    label: "neurology",
  },
  {
    category: "Science",
    human: "Q9215",
    id: "Q41630",
    label: "psychoanalysis",
  },
  {
    category: "Science",
    human: "Q9041",
    id: "Q101333",
    label: "mechanical engineering",
  },
  {
    category: "Science",
    human: "Q37064",
    id: "Q101929",
    label: "immunology",
  },
  {
    category: "Science",
    human: "Q37064",
    id: "Q243748",
    label: "bacteriology",
  },
  {
    category: "Lit",
    human: "Q5673",
    id: "Q131539",
    label: "children's literature",
  },
  { category: "Lit", human: "Q5673", id: "Q699", label: "fairy tale" },
  { category: "Lit", human: "Q5673", id: "Q699", label: "fairy tale" },
  {
    category: "Science",
    human: "Q55021352",
    id: "Q1069",
    label: "geology",
  },

  { category: "Science", human: "Q9106", id: "Q413", label: "physics" },
  { category: "Science", human: "Q9106", id: "Q413", label: "physics" },
  {
    category: "Science",
    human: "Q9106",
    id: "Q1069",
    label: "geology",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q394",
    label: "metrology",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q394",
    label: "metrology",
  },
  {
    category: "Science",
    human: "Q9106",
    id: "Q2329",
    label: "chemistry",
  },
  {
    category: "Art",
    human: "Q9106",
    id: "Q8134",
    label: "8134 was science",
  },
  { category: "Science", human: "Q9021", id: "Q413", label: "physics" },
  { category: "Science", human: "Q9021", id: "Q413", label: "physics" },
  {
    category: "Science",
    human: "Q9021",
    id: "Q3194786",
    label: "quantum theory",
  },
  {
    category: "Lit",
    human: "Q9021",
    id: "Q11473",
    label: "thermodynamics",
  },
  {
    category: "Science",
    human: "Q9021",
    id: "Q18362",
    label: "theoretical physics",
  },
];
