name: CI

on:
  push:
  pull_request:

env:
  VERCEL_GIT_COMMIT_REF: TBD
  VERCEL_GIT_COMMIT_SHA: TBD
  VERCEL_GIT_COMMIT_MESSAGE: TBD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Check
        run: pnpm --recursive run check
      - name: Map Fields of Work
        run: pnpm run update:fows
      - name: CLI Smoke Test
        run: pnpm --filter=@accomplishedh/cli run e2e:smoke
      - name: Lint
        run: pnpm --recursive run lint
      - name: Build
        run: pnpm --recursive run build
      - name: Test
        run: pnpm --recursive run test
      - name: Refresh SSR Wikibase Data
        run: pnpm run update:fows
